# fly.toml app configuration file generated for rakcdn-refresh-api on 2024-12-19T00:18:06+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rakcdn-refresh-api'
primary_region = 'lhr'

[processes]
app = "/bin/sh -c '/app/bin/migrate && /app/entry start'"

[build]

[env]
  NODE_ENV = "production"
  PORT = "2005"
  HOST = "0.0.0.0"

[http_service]
  internal_port = 2005
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
